artifact_location: /Users/mottad/Library/CloudStorage/OneDrive-LuxotticaGroupS.p.A/Desktop/corso
  python/example-model-main/mlflowruns/0
creation_time: 1731515035560
experiment_id: '0'
last_update_time: 1731515035560
lifecycle_stage: active
name: Default
